services:
  app-staging:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${STAGING_PORT}:${STAGING_PORT}"
    environment:
      - PORT=${STAGING_PORT}
    container_name: app-staging